version: "3.2" # https://docs.docker.com/compose/compose-file/compose-versioning/#version-3

services:
  cyberchef:
    image: mpepping/cyberchef
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Chicago
    deploy:
      replicas: 1      
    networks:
      - swarm_default
    ports:
      - 8084:8000

networks:
  swarm_default:
    external: true