version: '3'

services:
  keycloak:
    image: jboss/keycloak
    env_file: /var/data/config/keycloak/keycloak.env
    volumes:
      - /etc/localtime:/etc/localtime:ro    
    networks:
      - swarm_default
    ports:
      - 8086:8080
      - 9990:9990
    deploy:
      replicas: 1

networks:
  swarm_default:
    external: true
  
